# Generated by Django 6.0.4 on 2026-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rental Cars Morocco', max_length=100, verbose_name='Nom du site')),
                ('site_description', models.TextField(blank=True, verbose_name='Description du site')),
                ('site_logo', models.ImageField(blank=True, upload_to='site/logo/', verbose_name='Logo du site')),
                ('site_favicon', models.ImageField(blank=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('site_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('site_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('site_address', models.TextField(blank=True, verbose_name='Adresse')),
                ('site_footer', models.TextField(blank=True, verbose_name='Texte du pied de page')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('site_theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=10, verbose_name='Thème')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
