# Generated by Django 6.0.4 on 2026-04-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (classe CSS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='categories/icons/', verbose_name='Icône')),
                ('image', models.ImageField(blank=True, upload_to='categories/images/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique'), ('semi_auto', 'Semi-automatique')], default='manual', max_length=20, verbose_name='Transmission')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], default='gasoline', max_length=20, verbose_name='Carburant')),
                ('seats', models.PositiveIntegerField(default=5, verbose_name='Places')),
                ('doors', models.PositiveIntegerField(default=4, verbose_name='Portes')),
                ('luggage_capacity', models.PositiveIntegerField(default=2, verbose_name='Capacité bagages (valises)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage')),
                ('registration_city', models.CharField(blank=True, max_length=100, verbose_name="Ville d'immatriculation")),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix journalier (MAD)')),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix hebdomadaire (MAD)')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix mensuel (MAD)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caution (MAD)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('availability_status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('rented', 'Loué'), ('maintenance', 'Maintenance')], default='available', max_length=20, verbose_name='Statut de disponibilité')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Disponible à partir du')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='fleet.brand', verbose_name='Marque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='fleet.category', verbose_name='Catégorie')),
                ('features', models.ManyToManyField(blank=True, related_name='cars', to='fleet.carfeature', verbose_name='Équipements')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fleet.rentalcar', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', '-is_featured'],
            },
        ),
    ]
